extern const double t_0;
extern const double t_1;
extern const int N;
extern const int D;
extern const double G;
extern const int S;
extern const double initial_positions[N][D];
extern const double initial_velocities[N][D];
extern const double initial_mass[N];